### ISSUE TITLE
The bat file does not work

### ISSUE THREAD

**Issue by Aurora1203** [PratyushTripathy/Land-Cover-Using-Machine-Learning#3]
Dear sir, the bat file does not work on my side. It terminates automatically and says python installation failed. Any other solution?

**Comment by Aurora1203** [comment]
I can hardly believe that I spent almost the whole day installing GDAL and failed. Your bat file does not work. I tried to install step by step manually and still stuck to the GDAL 3.1.3 installation. All the other steps work, it stuck after I clicked for all users. Any idea about it? Thanks a lot.

**Comment by Aurora1203** [comment]
I tried and watched all your video, unfortunately, still got this error, when I come to python 37 for "import gdal"

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\osgeo\__init__.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\Python37\lib\site-packages\osgeo\__init__.py", line 32, in <module>
    _gdal = swig_import_helper()
  File "C:\Python37\lib\site-packages\osgeo\__init__.py", line 31, in swig_import_helper
    return importlib.import_module('_gdal')
  File "C:\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'

Could you plz kindly help me here?

**Comment by PratyushTripathy** [comment]
@Aurora1203 See [this](https://github.com/PratyushTripathy/python_gdal_automated_windows/tree/main/debugger).
